# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Internship Newsletter

on:
  schedule:
    - cron: '* * * * MON'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gspread markdown2 beautifulsoup4
    # Save files
    - shell: bash
      env:
        CREDS: ${{ secrets.GOOGLE_SHEETS_API_JSON }}
        PASS: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "$CREDS" > gcred.json
        echo "$PASS" > pass.txt
    # Send Email
    - name: Send Email
      run: python newsletter.py
